# Generated by Django 3.1.7 on 2021-03-28 07:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210328_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 28, 12, 7, 46, 249719)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 28, 12, 7, 46, 258726)),
        ),
    ]
