# Generated by Django 3.1.7 on 2021-03-28 07:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0004_auto_20210328_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='working',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 28, 12, 16, 57, 845672)),
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 28, 12, 16, 57, 855686)),
        ),
    ]
